#!/bin/sh

. /lib/functions.sh

case "$ACTION" in
pressed)
	return 5
;;
timeout)
	. /etc/diag.sh
	set_state failsafe
;;
released)
	if [ "$SEEN" -gt 5 -a "$SEEN" -lt 10 ]
	then
		echo "REBOOT WIFI" > /dev/console
		sync
		logger "resetting wifi"
		sleep 2
		wifi-reset-and-reboot
		exit 0
	elif [ "$SEEN" -gt 25 ]
	then
		echo "FACTORY RESET" > /dev/console
		logger "resetting to factory defaults"
		sleep 2
		rm /root/.osjs/settings.json
		jffs2reset -y && reboot &
		exit 0
	fi
;;
esac

return 0
